openapi: 3.0.3
info:
  title: Baserow API spec
  version: 1.32.5
  description: 'For more information about our REST API, please visit [this page](https://baserow.io/docs/apis%2Frest-api).


    For more information about our deprecation policy, please visit [this page](https://baserow.io/docs/apis%2Fdeprecations).'
  contact:
    url: https://baserow.io/contact
  license:
    name: MIT
    url: https://gitlab.com/baserow/baserow/-/blob/master/LICENSE
paths:
  /api/sso/oauth2/callback/{provider_id}/:
    get:
      operationId: oauth_provider_login_callback
      description: Processes callback from OAuth2 provider and logs the user in if successful.
      parameters:
      - in: query
        name: code
        schema:
          type: string
        description: The code returned by the IDP.
      - in: path
        name: provider_id
        schema:
          type: integer
        description: The id of the provider for which to process the callback.
        required: true
      tags:
      - Auth
      responses:
        '302':
          description: No response body
  /api/sso/oauth2/login/{provider_id}/:
    get:
      operationId: oauth_provider_login_redirect
      description: Redirects to the OAuth2 provider's authentication URL based on the provided auth provider's
        id.
      parameters:
      - in: query
        name: original
        schema:
          type: integer
        description: The relative part of URL that the user wanted to access.
      - in: path
        name: provider_id
        schema:
          type: integer
        description: The id of the provider for redirect.
        required: true
      - in: query
        name: workspace_invitation_token
        schema:
          type: string
        description: The invitation token sent to the user to join a specific workspace.
      tags:
      - Auth
      responses:
        '302':
          description: No response body
  /api/sso/saml/acs/:
    post:
      operationId: auth_provider_saml_acs_url
      description: Complete the SAML authentication flow by validating the SAML response. Sign in the
        user if already exists in Baserow or create a new one otherwise. Once authenticated, the user
        will be redirected to the original URL they were trying to access. If the response is invalid,
        the user will be redirected to an error page with a specific error message.It accepts the language
        code and the workspace invitation token as query parameters if provided.
      tags:
      - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SAMLResponse'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SAMLResponse'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SAMLResponse'
        required: true
      responses:
        '302':
          description: No response body
  /api/sso/saml/login/:
    get:
      operationId: auth_provider_saml_sp_login
      description: This is the endpoint that is called when the user wants to initiate a SSO SAML login
        from Baserow (the service provider). The user will be redirected to the SAML identity provider
        (IdP) where the user can authenticate. Once logged in in the IdP, the user will be redirected
        back to the assertion consumer service endpoint (ACS) where the SAML response will be validated
        and a new JWT session token will be provided to work with Baserow APIs.
      parameters:
      - in: query
        name: email
        schema:
          type: string
        description: The email address of the user that want to sign in using SAML.
      - in: query
        name: language
        schema:
          type: string
        description: 'An ISO 639 language code (with optional variant) selected by the user. Ex: en-GB.'
      - in: query
        name: original
        schema:
          type: string
        description: The url to which the user should be redirected after a successful login or sign up.
      - in: query
        name: workspace_invitation_token
        schema:
          type: string
        description: If provided and valid, the user accepts the workspace invitation and will have access
          to the workspace after login or signing up.
      tags:
      - Auth
      responses:
        '302':
          description: No response body
  /api/sso/saml/login-url/:
    get:
      operationId: auth_provider_login_url
      description: Return the correct redirect_url to initiate the SSO SAML login. It needs an email address
        if multiple SAML providers are configured otherwise the only configured SAML provider signup URL
        will be returned.
      parameters:
      - in: query
        name: email
        schema:
          type: string
        description: The email address of the user that want to sign in using SAML.
      - in: query
        name: language
        schema:
          type: string
        description: 'An ISO 639 language code (with optional variant) selected by the user. Ex: en-GB.'
      - in: query
        name: original
        schema:
          type: string
        description: The url to which the user should be redirected after a successful login.
      - in: query
        name: workspace_invitation_token
        schema:
          type: string
        description: If provided and valid, the user accepts the workspace invitation and will have access
          to the workspace after login or signing up.
      tags:
      - Auth
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
          description: ''
        '400':
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Machine readable error indicating what went wrong.
                    enum:
                    - ERROR_SAML_INVALID_LOGIN_REQUEST
                  detail:
                    oneOf:
                    - type: string
                      format: string
                      description: Human readable details about what went wrong.
                    - type: object
                      format: object
                      description: Machine readable object about what went wrong.
          description: ''
components:
  schemas:
    SAMLResponse:
      type: object
      properties:
        SAMLResponse:
          type: string
          description: The encoded SAML response from the IdP.
        RelayState:
          type: string
          description: The frontend URL where redirect the authenticated user.
      required:
      - RelayState
      - SAMLResponse
tags: []
