// Generated by baserow-cli

export interface NewsletterUsersRow {
  id: number;
  order: string;
  Email: string;
  Unsubscribed?: boolean;
  'Created on'?: any;
}

export interface CharityWebsiteEntriesRow {
  id: number;
  order: string;
  'Full Name': string;
  'Email Address'?: string;
  'Organization Name'?: string;
  'Current Website'?: string;
  Mission?: string;
  Goals?: string;
  Availability?: 'Yes' | 'No' | 'Maybe';
  Blog?: 'Yes' | 'No';
  Newsletter?: boolean;
}

